setono_sylius_shipmondo_global_webhook:
    path: /shipmondo/webhook
    defaults:
        _controller: webhook.controller::handle
        type: 'shipmondo'

setono_sylius_shipmondo_global_debug_webhook_index:
    path: /shipmondo/debug-webhook
    methods: [GET]
    defaults:
        _controller: setono_sylius_shipmondo.controller.debug_webhook::index
        
setono_sylius_shipmondo_global_debug_webhook_decode:
    path: /shipmondo/debug-webhook/decode
    methods: [POST]
    defaults:
        _controller: setono_sylius_shipmondo.controller.debug_webhook::decode
